import {
  LayoutDashboard,
  Settings,
  ScrollText,
  ShoppingCart,
  Shirt,
  Users,
  Warehouse,
  PieChart,
  Layers,
  Ruler,
  TrendingUp,
  AlertTriangle,
  Hash,
  Box,
  Building2,
  Receipt,
  Wallet,
  CreditCard,
  ShieldCheck,
  UserCog
} from "lucide-react";

export const allNavigation = [
  { name: "Dashboard", href: "/dashboard", icon: LayoutDashboard, permission: "view_dashboard" },
  { name: "POS Terminal", href: "/pos", icon: ShoppingCart, permission: "access_pos" },
  { name: "Products", href: "/products", icon: Shirt, permission: "manage_products" },
  { name: "Categories", href: "/categories", icon: Layers, permission: "manage_categories" },
  { name: "Sizes", href: "/sizes", icon: Ruler, permission: "manage_sizes" },
  { name: "Bank Accounts", href: "/masters/banks", icon: Building2, permission: "manage_banks" },
  { name: "Expense Master", href: "/masters/expense-categories", icon: Layers, permission: "manage_expense_categories" },
  { name: "Expenses", href: "/pos/expenses", icon: Receipt, permission: "access_expenses" },
  { name: "Customer Khata", href: "/pos/ledger", icon: Wallet, permission: "view_ledger" },
  { name: "Customers", href: "/customers", icon: Users, permission: "view_customers" },
  { name: "Inventory", href: "/inventory", icon: Warehouse, permission: "view_inventory" },
  { name: "Bill Profit", href: "/reports/bill-profit", icon: ScrollText, permission: "view_bill_profit" },
  { name: "Business P&L", href: "/reports/pnl", icon: PieChart, permission: "view_pnl" },
  { name: "Item Performance", href: "/reports/item-profit", icon: TrendingUp, permission: "view_item_profit" },
  { name: "Stock Valuation", href: "/reports/stock-summary", icon: Warehouse, permission: "view_stock_summary" },
  { name: "Low Stock", href: "/reports/low-stock", icon: AlertTriangle, permission: "view_low_stock" },
  { name: "Category Report", href: "/reports/category", icon: Layers, permission: "view_category_report" },
  { name: "Batch Tracking", href: "/reports/batch", icon: Box, permission: "view_batch_report" },
  { name: "Serial Tracking", href: "/reports/serial", icon: Hash, permission: "view_serial_report" },
  { name: "Invoice Center", href: "/invoices", icon: ScrollText, permission: "access_invoices" },
  { name: "User Roles", href: "/masters/roles", icon: ShieldCheck, permission: "manage_roles" },
  { name: "Employee Management", href: "/settings/employees", icon: UserCog, permission: "manage_employees" },
  { name: "Global Customers", href: "/admin/customers", icon: Users, roles: ["super_admin"] },
];

export const allBottomNav = [
  { name: "Settings", href: "/settings", icon: Settings, permission: "system_config" },
];
